### ISSUE TITLE
YANOM from Nimbus Note

### ISSUE THREAD

**Issue by gobbletown** [kevindurston21/YANOM-Note-O-Matic#67]
Nimbus Note is 'yet another' proprietary PKM app that imports notes from various other platforms nicely, but its export function for its own note type is abysmal.  It uses a wonky proprietary HTML export that divides each note into a .zip file that includes for each note exported: one .html file called "note" (gives the same filename for every note exported) + an "assets" folder (fonts, .css, and .jpg, etc.).  The links are created with "@" and do not automatically create backlinks.  It seems Nimbus Notes is using the same weblink system as their old "Everhelper dot me" product, if that helps any.

**Describe the solution you'd like**
Please add a YANOM for converting Nimbus Note (nimbusweb dot me) to .md or Obsidian Markdown.

**Describe alternatives you've considered**
YANOM, various pandoc GUI offerings, Total Commander and similar file programs.

**Additional context**
It seems Nimbus Notes is using the same weblink system as their old "Everhelper dot me" product, if that helps any.

**Comment by gobbletown** [comment]
Nimbus also offers .pdf export of each note, though not sure if that preserves any functional formatting for conversion to .md or maintaining links.

**Comment by thehistorianandthegeek** [comment]
Thanks.  I'll take a look and see what can be done.

**Comment by gobbletown** [comment]
Any luck @thehistorianandthegeek ?

**Comment by kevindurston21** [comment]
Hi,

Sorry tied up with other things there for a while.

Nimbus notes is horrible!  It is the worst of the note systems I've looked at so far for making un-reusable notes.  There is a message board on their site with people asking for better exports, but it looks like they will not do it as part of the business model will be to trap users into the system.  Once content is added to nimbus the formatting on the exported HTML is very CSS heavy so that only a web browser could view the page.  And they only export one page a time.  The hope being users can not face the effort to escape the system and keep paying.

I see several discussing around the web asking the same thing so a worthy challenge to start working on.

I can see it should be possible to convert the notes.  There will be some limitations....
- It will take some time to code up and get working - depending on how much time I have and how involved it will be anything from a few days to a few weeks before it's working.
- Will be fragile if they change their CSS formatting regularly
- No tags will be included (as they are not exported).
- The annoying one page at a time Nimbus export will need to be used to get the data out before conversion.

I'm sure there will be more issues as things move along.  If you have any sample pages, the more complex the better,  that you could export and share would help with testing.  

I have YANOM version 1.6.0 completed for release since September but issues with creating python distributions for linux/docker have held that up.  I'll get that out for windoze and Mac today/tomorrow and then work on the Nimbus conversion.

Cheers,

Kevin

**Comment by gobbletown** [comment]
Thanks so much Kevin!  

Your description of the _**Note Hostage Situation**_ with Nimbus is spot on.  And this is exactly the kind of thing that **YANOM-NOM** and the _non-YANOM-NOM YANOMs_ are battling.  I've started to notice the rising chorus of discontent from other Nimbus _note hostages_ on their message board too.  

Here's hoping this continues to increase awareness and feedback from Users to locked & closed systems!

Will attach some .zips of exports of HTML files.

Of note, there is a second option to export to PDF.  Is there a way to develop a NOM that exports text _and_ tags/links from the PDF files?

Thanks again for fighting the good fight!

Gobs

**Comment by kevindurston21** [comment]
I haven't paid for nimbus so cant generate any pdf's if you have could you send a couple and I'll take a look.   

I think the issue with pdfs will be that any embedded attachments will be missing, it will just produce a 'static' image so links to xlsx, docx, other pdf's will not be there and nor will the actual files.  

I think HTML route is the bet way for now.  I did see nimbus posted a comment they would work on a bulk export into their own export format.... so they'll probably make that unreadable for notes rescue!

Kev

**Comment by kevindurston21** [comment]
Hi,

It's looking very promising.  Still quite a bit of work to do but I have managed to extract all data from several pages.  The large table below shows what will be supported.  Which is everything that Markdown can support.  All the features I've found in Nimbus can be extracted, including the blocks/columns layout.  There is even a "manual" , and relatively easy, option for users to save their tags from being lost.  Each user will decide to invest the 30 seconds per page, before exporting, or not.

I've got another day or so of work tidying up and improving data structures and the algorithms to make something that can be used or easily modified for other note systems that export HTML heavy in proprietary CSS code.

The next, very easy step, is to build a Markdown file from the raw data, this can then be converted back to clean HTML or another markdown format using functionality already in YANOM.  

The only complicated parts left are
- file handling
    - extracting, reading large sets of exported notes 
    - renaming and moving assets and note files into a cleaner file organisation typical of markdown data sets.
    - recreate inter-note links.  
      - These are lost in the export but the NoteStation conversion also needs links recreated so hopefully can leverage off this work.  
      - As with NoteStation there will be limitations to what can be relinked cleanly.  
      - If there are two notes with the same name both will be linked to, (two links will be inserted in stead of one) as it is not possible to tell which is the correct file
      - If a note is renamed after a link is inserted the link will not be recreated.  
          - However if there is a single link in any note that has been created after the note has been renamed then the links with the old wrong name can also be made to work.


This last item will be straight forward
- Integrate fully into YANOM for reporting on issues seen in notes (links that may not be recreated, missing files/images 

|Coding Status|TO DO|Nimbus Feature | Conversion Result|
|---|---|---|---|
|Data Extracted|Generate MD content|Note data in 'blocks' (columns)|Yes, each block left to right is listed down the new note page in order<br>1 \| 2 \| 3<br>becomes<br>1<br>2<br>3|
|Data Extracted|Generate MD content|Paragraph Text|Yes|
|Data Extracted|Generate MD content|**Bold** formatting|Yes|
|Data Extracted|Generate MD content|<u>Underlined</u> format | No, not in MD specs, will be bold and italic|
|Data Extracted|Generate MD content|*Italic* format|Yes|
|Data Extracted|Generate MD content|~~Strikethrough~~ format| Yes|
|Data Extracted|Generate MD content|==Highlighting==| Yes, will add export option to use `==` or  `<mark>` or as plain text |
|Data Extracted|Generate MD content|Coloured text| No, plain text|
|Data Extracted|Generate MD content|Placeholder format| No, plain text|
|Data Extracted|Generate MD content|Headings|Yes|
|Data Extracted|Generate MD content|Checklists| Yes, including indentation levels|
|Data Extracted|Generate MD content|Numbered lists| Yes, including indentation levels|
|Data Extracted|Generate MD content|Bullet lists| Yes, including indentation levels|
|Data Extracted|Generate MD content|Captions on images etc| Yes, text formation as above|
|Data Extracted|Generate MD content|Pasted in images|Yes|
|Data Extracted|Generate MD content|Inserted images| Yes|
|Data Extracted|Generate MD content|Inserted files| Yes, as link to file|
|Data Extracted|Generate MD content|Section break lines |Yes|
|Data Extracted|Generate MD content|Hyperlinks|Yes|
|Data Extracted|Generate MD content|Code Sections|Yes, including code type (Python etc)|
|Data Extracted|Generate MD content|Date stamps|Yes|
|Data Extracted|Generate MD content|Block quotes|Yes|
|Data Extracted|Generate MD content|Hints| Become block quotes|
|Data Extracted|Generate MD content|Toggle block|Become bullet list|
|Done|Using HTML|Embedded iframe (e.g. youtube)|Yes|
|Done|Using HTML|Embedded blockquote (e.g. twitter tweet)|Yes|
|Data Extracted|Generate MD content|Bookmark|Yes, becomes link|
|Data Extracted|Generate MD content|Embedded audio recording|Yes, becomes link|
|Data Extracted|Generate MD content|Embedded screen/video recording|Yes, becomes link|
|Data Extracted|Generate MD content|Button|Yes, becomes link|
|Data Extracted|Develop TOC builder|Outline|Regenerate a numbered table of contents in MD format|
|Data Extracted|Generate MD content|Mentions of people|Yes, plain text or links where mention has an email address|
|Data Extracted|Create matching routine, hopefully building off existing one used in NSX|Links to "workspaces"| MD does not have a "notebook" to link to. If workspace name matches a folder in export data set a link to that folder `file:/folder/path` can be created|
|Data Extracted|Create matching routine, hopefully building off existing one used in NSX|Links to notes in same workspace| Yes - If export file name matches the link file name links will be regenerated |
|Data Extracted|Create matching routine, hopefully building off existing one used in NSX|Links to notes in a different workspace| Yes - if linked to note is also in the export folder|
|Data Extracted|Generate MD|`#tags`|Yes, BUT USER ACTION REQUiRED BEFORE EXPORT.|

- Tags are not exported from Nimbus. 
- If tags are important a manual process is required before export
	- User selects all the the tags in one mouse swipe and copy and pastes into top of the note.
	- User adds `#` in front of tag words.
	- YANOM will read them and generate real tags in markdown / html

![image](https://user-images.githubusercontent.com/43143552/148623786-490271bd-1dce-4726-94cb-1bd7e0d71ee0.png)

**Comment by kevindurston21** [comment]
Just an update on progress.

As an experiment I wrote a html to markdown parser for nimbus html.  YANOM normally cleans HTML and uses pandoc.  

This parser would mean no need for pandoc and the two zip files attached are the input and output.  Not all the note links int his example are linked as the single file was processed.  If the linked to note files had been included in the processing all the links would have been restored.

The parser works fine, and almost every feature in nimbus is supported, but there is a potential issue with pasted in content from other websites that the parser also needs to attempt to parse.  It was an interesting experiment and the 2000 lines will be kept for future work.

Currently I'm using a html cleaning routine as used in NSX files to add to the next release and may come back to in house parsing instead of pandoc in the future.   The HTML and pandoc approach needs more fudging pre and post conversion to overcome pandoc limitations but will do for now.  The result but may end up slightly less featured that the direct parser example attached.  For example an embedded pdf will be a hyperlink after pandoc, not an displayed embedded file.

Hopefully it won't take too long perhaps a week...time permitting.

[a test note23 - markdown.zip](https://github.com/kevindurston21/YANOM-Note-O-Matic/files/7945589/a.test.note23.-.markdown.zip)
[a test note23 - niumbus.zip](https://github.com/kevindurston21/YANOM-Note-O-Matic/files/7945592/a.test.note23.-.niumbus.zip)

**Comment by kevindurston21** [comment]
Hi,

It is progressing but will be a while yet.  In the last week I quickly reverted back to the new html  to markdown parser approach as in the long run it should be easier to add additional note formats.  

I've been simplifying the html dat extraction algorithm and have been refactoring that and the HTML and Markdown re-creation.

I'm going to have a look at creating all the types of Markdown without using pandoc.  I can create Git-flavoured and Obsidian already, but I may leave this to the next revision if I can't come up with a quick approach that is not ugly code.

Then It's just some integration to the rest of YANOM still to do.  Once I've done the integration I'll make a pre-release and let you know, any testing with notes will help as there is often some weird formatting or behaviour that comes out. 

I keep finding weird things in the nimbus notes, for example the default getting started page has content that I can't duplicate in the system itself....  But I've added handling for that as well incase it is there and I can't create it or it is something that will appear.

I also found that any audio file is coded in the nimbus HTML with he wrong file extension (all are coded as `mp3` and all are saved in the exported assets with a `mpga` extension even if they are neither mp3's or mpga's.   Some markdown viewers could play them some could not.  I now check their real file type and correct the note content and the extension on the file itself.

Kevin

**Comment by kevindurston21** [comment]
Hi,

Finally have a version ready for release.  Managed to get some more time in this this week and I am about to put a 1.7.0 beta release up.  If you have time to do some tests I'd appreciate any issues you find.

The final approach is a new way of parsing HTML into data and then taking that data and recreating a 'clean' simple HTML or markdowm file, and no longer uses pandoc, but this means for nimbus there is no 'pandoc markdown' format if somebody needs that in the future a convert using pandoc  can be added to get that.

The markdown output is not excessively strict to type, for example commonmark does not support checklists but nearly every body uses commonmark with extensions so I have left the checklists in place.

YANOM was 2423 code lines, this added a new 2390 lines but hopefully any additional note formats needing to be converted can be added relatively straight forwardly, though I have some other structural changes to make over time to make this easier.  Plus I will move the old conversion (nsx and html) to the new approach.

## How to use the nimbus conversion

1. If you want to keep any tags.  /you have to select them on the nimbus page/app and copy them to the top of the note itself so that they get exported.
copy
![image](https://user-images.githubusercontent.com/43143552/155858424-02af1278-ea9b-4076-b901-81430890164c.png)
paste
![image](https://user-images.githubusercontent.com/43143552/155858480-93d2f894-933a-443a-9a15-8aee20d070a4.png)
add a `#` in front of each tag so YANOM can find them
![image](https://user-images.githubusercontent.com/43143552/155858444-c6185d8f-72e3-40df-9bdd-a4bd95c72561.png)

The tags will be located and added to a markdown front matter section.

2. Export each note as HTML.  Place each zip file in a folder, if you want to keep the same folder layout as in nimbus organise them that way.

For example
![image](https://user-images.githubusercontent.com/43143552/155858281-d62c684f-ba82-438f-99ee-fdfd5361ec0f.png)

3. Run YANOM choose nimbus as input, quick settings for gfm and obsidian or manual to choose options as for the other conversions
- The specific nimbus options are
    - 4 lists of file types that can be embedded.   These decide if a markdown link is  embedded with `!` - `![display text](file.pdf)`  or no `!` `[display text](file.pdf)`.  These embed types vary by markdown viewer so are not specifically nimbus and this option will be added to the other conversion eventually allowing users to optimise links for the markdown viewer they will be using.
    - Keep nimbus row and column headers - these are the 123, ABC style row column headers
    - unrecognised tag format - if a HTML tag is not recognised it can be passed through as it is or the text elements stripped from it and just the text passed to the exported file.  

Any unrecognised tags are recorded in the warning log,  and can provide feedback for any tags needing additional support. It is also useful when converting a new format of note, you quickly get a list of all custom tags that need to be handled.
 
## Features supported

|Nimbus Feature | Conversion Support|
|---|---|
|Note data in 'blocks' (columns)|Yes, each block left to right is listed down the new note page in order<br>Block 1 \| Block 2 \| Block 3<br>becomes<br>Block 1<br>Block 2<br>Block 3|
|Paragraph Text|Yes|
|**Bold** formatting|Yes|
|<u>Underlined</u> format | Yes, but using inline html with `<u>` tag where markdown format allows use of HTML|
|*Italic* format|Yes|
|~~Strikethrough~~ format| Yes|
|==Highlighting==| Yes, using `<mark>` |
|Multiple "stacked" formats such as ~~***==bold, italic highlight strikethrough==***~~| Yes |
|Coloured text| Yes, returned as inline html where supported|
|Placeholder format| No, plain text|
|Inline `code`| Yes|
|Headings|Yes, and text formatting as above|
|Checklists| Yes, including indentation levels and text formatting as above|
|Numbered lists| Yes, including indentation levels and text formatting as above|
|Bullet lists| Yes, including indentation levels and text formatting as above|
|Captions on images etc| Yes, and text formatting as above|
|Pasted in images|Yes|
|Inserted images| Yes, but note that the original file names are not maintained in nimbus and will be similar to `0UJGinY2jASIj13F.png`|
|Embedded files - i.e. pdfs, videos, audio recordings that are visibly displayed on nimbus page|Yes.  Original file name is restored. Audio file extensions that are incorrect from nimbus are corrected. Markdown uses `![file name - caption text](/path.to/file)` format that will display as an image/live file display/in a player where supported by the markdown viewer. HTML will be a simple link to the file.|
|Hyperlinks|Yes|
|Section break lines |Yes|
|Code Sections|Yes, including code type (Python etc)|
|Tables|Yes, option to keep the 'ABC' and '123' spreadsheet row  and column labels.  See below for table items|
|Table cell text and numbers|Yes|
|Table cell with inserted file link |No, Not exported by nimbus note|
|Table cell checkboxes|Yes, including checked status, but as inline html `<input type="checkbox" checked>` as MD does not support block level items in tables|
|Table cell select buttons|Yes, plain text|
|Table cell people mentions|Yes|
|Table cell collaborator mentions|Yes|
|Table cell date entry|Yes|
|Table cell hyperlinks|Yes|
|Table cell ratings|Yes as text `Rating 3/5 stars`|
|Table cell progress bar|Yes, but data is not exported from nimbus note, exports 0%. Functionality is coded, if nimbus fixes the export the correct % will appear.|
|Date stamps|Yes|
|Block quotes|Yes|
|Hints| Yes, become block quotes|
|Toggle block|Yes, becomes bullet list|
|Embedded iframe (e.g. youtube)|Yes|
|Embedded blockquote (e.g. twitter tweet)|Yes, becomes set of links, no java script|
|Bookmark|Yes, becomes link|
|Embedded audio recording|Yes, becomes link, file extension corrected|
|Embedded screen/video recording|Yes, becomes link|
|Button|Yes, becomes link|
|Outline|Yes, as a numbered table of contents that links to headers.<br>For gfm markdown anchor links are human readable.<br>For other formats links are id number and anchor is also placed next to headings<br>Outline links will not be created for commonmark as are not supported, common mark.org says use gfm format instead.<br>Working links will also depend on the markdown viewer program used as implementation is variable|
|Mentions of people|Yes, plain text or links where mention has an email address|
|Links to "workspaces"| Yes, but as link is to a folder it has to be an absolute URI in markdown. If the workspace name matches a folder in the export data set.  If a workspace is renamed after link is created it can be re-linked if there is a link to the new name in one of the notes in the set of notes being converted.<br>  <br>NOTE - these links DO NOT work at all in the original nimbus html files|
|Links to "folders"| Yes, but as link is to a folder it has to be an absolute URI in markdown. If the exported notes are organised in the same folder names and the mention matches a folder in the export data set, or if the folder has been renamed there is a link to the new folder name in one of the notes in the set of notes being converted. If there is more than one folder that matches the mention name links will be made to each folder.<br>  <br>NOTE - these links DO NOT work at all in the original nimbus html files|
|Links to other notes| Yes - If there is a converted note file of the same name links will be regenerated. If the note has been renamed since the link was created it will be linked to the new name if there is at least one link to that new name in the set of notes being converted.  If there is more than one note of the mention name a link will be made to each note of that name, to differentiate each of these links the displayed text also includes the folder the note is in. <br> <br>NOTE - these links DO NOT work at all in the original nimbus html files|
|`#tags`|Yes, tags and title will be in front matter section. But user action required to paste tags into top of note before export.|
|Files "Attached" above the note|Yes.  Nimbus has an attachment option that "attaches" files separate from the note content.  They are exported as assets but ARE NOT linked to in the exported nimbus HTML.  These files are added as links to the end/bottom of the note content.  <br><br>This process will also catch any files that are in the nimbus HTML that could not be, or were not, processed.|
|Task list on right of nimbus webpage| No.  This task list is not part of the note content exported from nimbus|
|Reminders | No.  Reminders are not part of the note content exported from nimbus|

**Comment by gobbletown** [comment]
Fantastic work!

Will try to get some testing in. 

A bonus is Nimbus seems to have unclogged the error it's always thrown when trying to export entire vaults at once!

Now at least I've fully freed my data (and as such, I wish Nimbus well in maintaining their user base by user choice not obligation).

Time to backup, test, and convert!

Woot!

**Comment by kevindurston21** [comment]
Hi,

Did you get anywhere on testing?  I have some other issues to address and wondering if to release with the nimbus conversion as well.

Thanks

Kevin

**Comment by kevindurston21** [comment]
Released a 1.7.0 full release version
